#!/usr/bin/env ruby
APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require File.expand_path('../../vendor/plugins/dbdump_command/lib/commands/dbdump',  __FILE__)
require APP_PATH
Rails::DBDump.start(Rails.application)
